name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          shellcheck_flags: '-x'
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          
      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@v3
        with:
          files: "**/*.{md,sh}"
          config: .cspell.json
          
      - name: Run install script
        run: |
          chmod +x install.sh
          ./install.sh --dry-run 